[agent]
  snmp_translator = "gosmi"

[[inputs.snmp]]
  agents = ["udp://127.0.0.1:9"]
  version = 2
  community = "${SNMP_COMMUNITY:?SNMP_COMMUNITY is required}"
  path = [
    "/usr/share/snmp/mibs",
    "/opt/telegraf/mibs",
  ]
  timeout = "100ms"
  retries = 0
  agent_host_tag = "source"

  [[inputs.snmp.field]]
    oid = "SNMPv2-MIB::sysName.0"
    name = "sysName"
    is_tag = true

  [[inputs.snmp.table]]
    oid = "IF-MIB::ifTable"
    name = "interface"
    inherit_tags = ["sysName"]

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      name = "ifDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifOperStatus"
      name = "oper_status"
      conversion = "enum"
